### ISSUE TITLE
[Bug] - Error shown in app when transferring money to or from a player

### ISSUE THREAD

**Issue by ChickenDipper1** [project-error/npwd_qb_banking#3]
Transferring money on the banking app works, but instead of the app showing a success message or reloading back to the apps main screen an error is displayed.
This also happens if I have the banking app open and another player transfers money to my account.

The money is sent and received even with the error appearing.

![image](https://user-images.githubusercontent.com/41157940/189189463-53883819-5b37-4d16-a8a4-30717585fa8b.png)

**Comment by xchopin** [comment]
same issue

**Comment by ChickenDipper1** [comment]
Fixed by applying: https://github.com/npwd-community/npwd_qb_banking/commit/c0ccc8aa95e1eca13676d476cd45381470e42817
